car = "volvo"
print("Is my car is volvo, I guess true")
print(car == "volvo")
print("Is my car is Volvo, I guess true")
print(car == "Volvo")

print("3 > 1, I guess true")
print(3>1)
print("3 > 3, I guess true")
print(3>3)
print("3 > 1 or 3 < 2, I guess true")
print(3>1 or 3 < 2)
print("3 > 1 and 3 < 2, I guess true")
print(3>1 and 3 < 2)
print("999 < -1 or 3 < 2, I guess true")
print(999 < -1)
print("999 < 1000 or 3 < 2, I guess true")
print(999 < 1000)
print("ford < volvo , I guess true")
print('ford' < 'volvo')
